wiki/README.md

docs: refine readme.

---

mlc_config.json
wiki/guide/resources.md

Resolves #39
Resolves https://github.com/BITNP/BIThesis/issues/405

doc: 补充学习资源

---

wiki/guide/resources.md

https://github.com/BITNP/BIThesis/pull/456

doc: LaTeX Tables Editor and `algorithm2e`

---

wiki/guide/resources.md

Resolves https://github.com/BITNP/BIThesis/issues/467

doc: `algorithm`宏包应当加选项按章编号

---

README.md

Relates-to: https://github.com/BITNP/BIThesis/commit/28a27ccc44a59c5524970890146a173029da989f

doc: 更新官方支持情况

---

renovate.json

现在更新得太频繁，远远超过需求，都干扰翻`glog`了。Netlify那边也不好一直这么更新。

ci: tell renovate to update less frequently

---

.github/lychee.toml
wiki/faq/bib-comma.md
wiki/faq/bib-split.md
wiki/faq/cover-dash.md
wiki/faq/hyphen.md
wiki/faq/longtable.md
wiki/faq/minted.md
wiki/faq/slow.md
wiki/faq/watermark.md

主要是复制粘贴，我预备直接合并。
Relates-to: #475

docs: 抄录若干 GitHub Discussions

---

wiki/guide/converting-to-word.md

docs: 补充转换 Word 的方法

---

wiki/.vitepress/config.mts
wiki/.vitepress/theme/faq_data.ts

[Prev Next Links | VitePress](https://vitepress.dev/reference/default-theme-prev-next-links)

feat: Add pre/next links to `/faq/*`

---

wiki/faq/symbols-bracket.md

https://deploy-preview-486--bithesis-wiki.netlify.app/faq/symbols-bracket.html

docs: Create symbols-bracket.md

---

wiki/guide/acknowledgements.md

update acknowledgements for 2024

update acknowledgements for 2024

---

wiki/.vitepress/theme/Contribution.vue
wiki/.vitepress/theme/contributors.data.ts
wiki/.vitepress/theme/contributors_data.ts
wiki/guide/acknowledgements.md

原来的表格有如下警告。
```log
[vitepress] warning: <tr> cannot be child of <table>, according to HTML specifications. This can cause hydration errors or potentially disrupt future functionality.
```
日后补充方法已记录在文件中。
https://bithesis.bitnp.net/guide/acknowledgements.html
https://deploy-preview-503--bithesis-wiki.netlify.app/guide/acknowledgements.html

refactor: 重构致谢页

---

wiki/faq/compiler-xelatex.md

最近有好几个人问。
https://deploy-preview-506--bithesis-wiki.netlify.app/faq/compiler-xelatex.html

docs: 空模板无法编译，换用 XeLaTeX

---

wiki/.vitepress/theme/contributors_data.ts
wiki/guide/acknowledgements.md

add myself as a wiki maintainer

---

wiki/faq/edit-const.md

Relates-to: https://github.com/BITNP/BIThesis/pull/624
已完成，但尚未发布版本，故请勿合并。

docs: edit-const 增加局部设置方法

---

wiki/faq/algorithm.md
wiki/faq/array-stretch.md
wiki/faq/clean.md

缓冲（2025年4月23日）
https://github.com/BITNP/BIThesis/discussions/586#discussioncomment-12918537

docs(faq): 更新 algorithm，增加 array-stretch

---

package.json
pnpm-lock.yaml
wiki/.vitepress/config.mts
wiki/.vitepress/naive-ui-adapter/config.ts
wiki/.vitepress/naive-ui-adapter/theme.ts
wiki/.vitepress/theme/Layout.vue
wiki/.vitepress/theme/PubAuthorAnnotation.vue
wiki/.vitepress/theme/index.ts
wiki/faq/bib-author.md
wiki/faq/pub-author-an.md

https://deploy-preview-525--bithesis-wiki.netlify.app/faq/pub-author-an.html
`package.json`变化：
- 增加 Naive UI
- 升级 vue 到 3.5，因为用了 [template ref](https://vuejs.org/guide/essentials/template-refs.html#template-refs)
- 本来已间接导入`@css-render/vue3-ssr`，但现在 Naive UI 需要直接用，故增加
`pnpm build`会显著变慢，`pnpm dev`还行。
（愈发认为 VitePress 难用）

feat: 生成`pub.bib`的`author+an`

---

wiki/.vitepress/config.mts
wiki/faq/biber-backend.md
wiki/guide/ask-computer.md
wiki/guide/preface.md

https://deploy-preview-522--bithesis-wiki.netlify.app/guide/ask-computer.html

添加询问人工智能的实例

---

wiki/faq/bib-url.md
wiki/faq/bithesis-dtx.md
wiki/faq/clear-double-page-style.md
wiki/faq/clear-double-page.md
wiki/faq/word-font.md

Resolves BITNP/BIThesis#666
Resolves #527

docs(faq): 补充

---

wiki/faq/cover-dash.md

docs: Replace timeout link
